[world]
name = "Realms World"
website = "https://realms.world/"
description = "DNC"
seed = "DNC"

[env]
chain_id = "SN_MAINNET"
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"
world_address = "0x7c2db2c4225bf87561faac0c9b93fa63a39ee306065e5ed0bf6e8d6c040fbbc"
world_block = 1712240

[namespace]
default = "ls_0_0_5"

[writers]
"ls_0_0_5" = [
    "ls_0_0_5-game_systems", 
    "ls_0_0_5-game_token_systems", 
    "ls_0_0_5-settings_systems",
    "ls_0_0_5-beast_systems",
    "ls_0_0_5-adventurer_systems"
]

[init_call_args]
"ls_0_0_5-game_token_systems" = [
    "0x01aebEB03D574e1B6c1c6D4E988b3cc3914705dE9Ec76B62D49967F26e616d4e",
    "0x070051630806034721bf9e374ac15a7d28ee655cd8909925384790edc737a002" # denshokan_address
]