[world]
name = "Provable Games"
description = "DNC"
seed = "pg-slot-10"

[env]
rpc_url = "https://api.cartridge.gg/x/pg-slot-3/katana"
# Default account for katana with seed = 0
world_address = "0x51b471d552deb71dcc6122cc79efdb2ad8feffa57d33e6077fb3acd33496b4a"

[namespace]
default = "ls_0_0_6"

[writers]
"ls_0_0_6" = [
    "ls_0_0_6-game_systems",
    "ls_0_0_6-game_token_systems",
    "ls_0_0_6-settings_systems",
    "ls_0_0_6-beast_systems",
    "ls_0_0_6-adventurer_systems"
]

[init_call_args]
"ls_0_0_6-game_token_systems" = [
    "0x0238df9Efd27Aba2ccB0bdC97a4cf440caA403e9ed3f1883294Ab6CDBA6C5282",
    "0x07fb67dae8765fe214b68fcd20d14b5d4784cedde759840559314f539aa04e32", # denshokan_address
    "1" # Option::None for renderer address
]