[world]
name = "Provable Games"
description = "DNC"
seed = "DNC"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x04c9c7bba8c218c1ee2f9d95f5cecf8b4cafbe8cf072390b69651e48519c1ebb"

[namespace]
default = "ls_0_0_6"

[writers]
"ls_0_0_6" = [
    "ls_0_0_6-game_systems", 
    "ls_0_0_6-game_token_systems", 
    "ls_0_0_6-settings_systems",
    "ls_0_0_6-beast_systems",
    "ls_0_0_6-adventurer_systems",
    "ls_0_0_6-objectives_systems"
]

[migration]
order_inits = [
    "ls_0_0_6-game_systems",
    "ls_0_0_6-loot_systems",
    "ls_0_0_6-renderer_systems",
    "ls_0_0_6-adventurer_systems",
    "ls_0_0_6-beast_systems",
    "ls_0_0_6-game_token_systems", 
    "ls_0_0_6-settings_systems", 
    "ls_0_0_6-objectives_systems"
]

[init_call_args]
"ls_0_0_6-game_token_systems" = [
    "0x065d2AB17338b5AffdEbAF95E2D79834B5f30Bac596fF55563c62C3c98700150", # account address
    "0x00cf3712b6168493d89be576f3ebdf0c76dcda964f952dacc21a72094b9e2899", # denshokan address
    "1" # Option::None for renderer address
]